### ISSUE TITLE
find_product from 2.0 API does not correctly handle search parameters

### ISSUE THREAD

**Issue by gianlucascoccia** [evonove/mkm-sdk#47]
I am trying to search for products using the find_parameters method from API 2.0. However, whenever I attempt a request I get the following error:

```
mkmsdk.exceptions.ConnectionError: Request failed
Status code: 400
Response message: Bad Request
b'{"mkm_error_description":"Provide a search string to search for.","internal_error_code":null,"post_data_field":null,"http_status_code":400,"http_status_code_description":"Bad Request","rfc2616_description_link":"http:\\/\\/www.w3.org\\/Protocols\\/rfc2616\\/rfc2616-sec10.html"}'
``` 

After some digging, I believe (but I'm not sure) that the issue is due to the api map, that is missing the necessary parameters:
```
"find_product": {
                    "url": "/products/find",
                    "method": "get",
                    "description": "Searches for products by a given search string",
```

The code I am using is the following:
```
mkm = Mkm(_API_MAP["2.0"]["api"], _API_MAP["2.0"]["api_root"])
for card_name in cards:
    # Call endpoint with specified parameters
    response = mkm.market_place.find_product(name=card_name)  # 1 is MtG
```

**Comment by silvanocerza** [comment]
The correct syntax for that call would be `mkm.market_place.find_product(params={'search': card_name})` since this call uses query parameters.

The syntax you used is for URL parameters, for example `mkm.market_place.user(user='SampleUser')` would format `https://api.cardmarket.com/ws/v1.1/output.json/user/{user}` as `https://api.cardmarket.com/ws/v1.1/output.json/user/SampleUser`, while `mkm.market_place.find_product(params={'search': card_name})` is `https://api.cardmarket.com/ws/v1.1/output.json/products/find?search=Black%20Lotus`

**Comment by gianlucascoccia** [comment]
I see! I tried and indeed works as intended when using query parameters. Thanks for the assistance.
